### ISSUE TITLE
Can't get validator info with special characters in the name

### ISSUE THREAD

**Issue by novy4** [kukabi/polkadot-kusama-1kv-telegram-bot#7] opened 2021-07-04 13:19 UTC
Hello

I have a chain symbol in the name of my validator. I can add it to the bot, but I can query rewards or other info about it. I get error:
⛓  Novy Validator ⛓ was not found.

Regards,
Alex

**Comment by kukabi** [comment] 2021-07-04 13:28
Thanks much for the report @novy4! Will take a look and fix it pretty soon.

**Comment by kukabi** [comment] 2021-07-04 14:44
Hi again @novy4, the fix for the issue is live now, please give it a try. I'm closing the issue, feel free to reopen it if the bug persists. Cheers!

**Closed by kukabi** 2021-07-04 14:44 UTC

**Comment by novy4** [comment] 2021-07-04 19:07
Works great now, thanks!
